/* English content is separate from rendering to support reviewed translations later. */
window.GUIDE_CONTENT = {
  devices: {android:'Android phone', iphone:'iPhone',tablet:'Android tablet',ipad:'iPad',windows:'Windows',mac:'Mac',linux:'Linux'},
  apps: {
    pingcoin:{name:'Pingcoin', androidName:'Pingcoin - Coin Ping Test',iosName:'Pingcoin: Gold & Silver Tester',androidDeveloper:'Pingcoin',iosDeveloper:'Jesse Szepieniec',androidURL:'https://play.google.com/store/apps/details?id=com.pingcoin.android.pingcoin',iosURL:'https://apps.apple.com/us/app/pingcoin-gold-silver-tester/id6754670308',
    access:'Start with the free tests offered in your app. If you need more, review the price and renewal terms before buying. Offers can differ between Android and Apple devices. A purchase on one platform may not unlock another.',
    testing:[['Choose the exact coin','Select the matching metal, weight and coin type. Check the year or design where relevant. Do not select the closest-looking coin if yours is absent.'],['Open the standard test','Follow the normal coin-testing screen. The documentation calls its recording control “Start Recording”; store images show different controls by version. Use the current app’s test control.'],['Capture and review','Use the illustrated Omega positioning and activation steps below to capture the coin’s ring, then let the app finish. Compare the result with weight, size and visual checks. Repeat an unclear result in a quieter setting.']],
    visualsAndroid:[['pingcoin-select.png','1 · Choose your coin','Official Android store image of the coin list. Match the metal and weight.'],['pingcoin-test.png','2 · Read the sound result','Official Android store image of a completed test. The screenshot may show an older version; it is not proof of authenticity.']],
    visualsApple:[['pingcoin-ios-3.webp','1 · Find the coin type','Official iPhone store artwork showing the coin list. Promotional text is part of the source image.']],
    source:'https://pingcoin.com/docs/how-to-use'},
    stackertools:{name:'StackerTools',androidName:'StackerTools App',iosName:'StackerTools App',androidDeveloper:'SoundMoneyMetals',iosDeveloper:'SoundMoneyMetals (seller: Sound Money, LLC)',androidURL:'https://play.google.com/store/apps/details?id=com.soundmoneymetals.stackertools',iosURL:'https://apps.apple.com/us/app/stackertools-app/id6502847897',
    access:'StackerTools is free to download. Full access may require a developer-issued code or purchase. Pocket Pinger owners can check their Bonus Pack for a code. Buying an Omega does not include a StackerTools license. Check the developer’s current access options before paying.',
    testing:[['Find the exact coin','On the home screen, choose the correct coin and design/year range. The web app labels this “Select a Coin or Bar to Begin a Sound Test.”'],['Check measurements and begin','The observed web test screen shows Diameter, Mass and Thickness and a “Start” control. Confirm the measurements against the actual coin; do not assume preset values are measurements of your coin. Button names may vary by app version.'],['Review the test','Use the illustrated Omega positioning and activation steps below, then let the app analyze the ring. Read its outcome and any request to confirm size or weight. A pass is one screening result, not a guarantee.']],
    visualsAndroid:[['stackertools-test.png','Test screen · Android','Official Google Play phone screenshot. Locate the coin name, Start control, sound plot and measurement fields.']],
    visualsApple:[['stackertools-ios-1.webp','A matching sound result','Official iPhone store screenshot. The green result also asks the user to confirm size and weight.'],['stackertools-ios-2.webp','A non-matching result','Official iPhone store screenshot showing a failed peak match. Recheck setup and coin selection before drawing a conclusion.']],
    source:'https://stackertools.com/home'}
  }
};
